#!/bin/sh

 ./gradlew check

 status=$?

 if [[ "$status" = 0 ]] ; then
     echo
     echo "✅ Everything went well"
     echo
     exit 0
 else
     echo
     echo 1>&2 "❌ Something went wrong, please review it first"
     echo
     exit 1
 fi
